export default {
    CREATE_COURSE:"CREATE_COURSE",
    LOAD_COURSES:"LOAD_COURSES",
    UPDATE_CURESE:"UPDATE_CURESE",
    DELETE_COURSE:"DELETE_COURSE",
    CREATE_AUTHOR:"CREATE_AUTHOR",
    LOAD_AUTHORS:"LOAD_AUTHORS",
    DELETE_AUTHOR:"DELETE_AUTHOR",
    UPDATE_AUTHOR:"UPDATE_AUTHOR"
}